In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv("Churn_Modelling.csv")
df

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [3]:
df.isna().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [4]:
df = df.drop_duplicates()

In [5]:
df

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [6]:
df['Geography'].unique()


array(['France', 'Spain', 'Germany'], dtype=object)

In [7]:
from sklearn.preprocessing import LabelEncoder
le =LabelEncoder()
df['Gender'] = le.fit_transform(df['Gender']) # Female = 0 | Male = 1
df['Geography'] = le.fit_transform(df['Geography'])
df

RowNumber  CustomerId    Surname  CreditScore  Geography  Gender  Age  \
0             1    15634602   Hargrave          619          0       0   42   
1             2    15647311       Hill          608          2       0   41   
2             3    15619304       Onio          502          0       0   42   
3             4    15701354       Boni          699          0       0   39   
4             5    15737888   Mitchell          850          2       0   43   
...         ...         ...        ...          ...        ...     ...  ...   
9995       9996    15606229   Obijiaku          771          0       1   39   
9996       9997    15569892  Johnstone          516          0       1   35   
9997       9998    15584532        Liu          709          0       0   36   
9998       9999    15682355  Sabbatini          772          1       1   42   
9999      10000    15628319     Walker          792          0       0   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [8]:
df['Geography'].unique()

array([0, 2, 1])

In [9]:
df1 = df.drop(columns =['RowNumber','Surname','CustomerId'],inplace =True)
df

CreditScore  Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619          0       0   42       2       0.00              1   
1             608          2       0   41       1   83807.86              1   
2             502          0       0   42       8  159660.80              3   
3             699          0       0   39       1       0.00              2   
4             850          2       0   43       2  125510.82              1   
...           ...        ...     ...  ...     ...        ...            ...   
9995          771          0       1   39       5       0.00              2   
9996          516          0       1   35      10   57369.61              1   
9997          709          0       0   36       7       0.00              1   
9998          772          1       1   42       3   75075.31              2   
9999          792          0       0   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0             1               1        101348.88       1  
1             0               1        112542.58       0  
2             1               0        113931.57       1  
3             0               0         93826.63       0  
4             1               1         79084.10       0  
...         ...             ...              ...     ...  
9995          1               0         96270.64       0  
9996          1               1        101699.77       0  
9997          0               1         42085.58       1  
9998          1               0         92888.52       1  
9999          1               0         38190.78       0  

[10000 rows x 11 columns]

In [10]:
X= df.drop(columns ='Exited')
Y =df[['Exited']]

from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test =train_test_split(X,Y,random_state =42,test_size =0.3)
X_train

CreditScore  Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
9069          619          2       0   32       4  175406.13              2   
2603          643          1       0   34       7  160426.07              1   
7738          561          0       1   33       6       0.00              2   
1579          618          1       1   41       8   37702.79              1   
5058          714          0       1   37       9  148466.93              2   
...           ...        ...     ...  ...     ...        ...            ...   
5734          768          0       1   54       8   69712.74              1   
5191          682          0       0   58       1       0.00              1   
5390          735          0       0   38       1       0.00              3   
860           667          0       1   43       8  190227.46              1   
7270          697          1       1   51       1  147910.30              1   

      HasCrCard  IsActiveMember  EstimatedSalary  
9069          1               1        172792.43  
2603          0               1        188533.11  
7738          0               0        173680.39  
1579          1               1        195775.48  
5058          0               1        151280.96  
...         ...             ...              ...  
5734          1               1         69381.05  
5191          1               1           706.50  
5390          0               0         92220.12  
860           1               0         97508.04  
7270          1               1         53581.14  

[7000 rows x 10 columns]

In [11]:
# APPLYING LOGISTIC REGRESSION
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
clf = lr.fit(X_train,Y_train) 
Y_pred = lr.predict(X_test)

In [12]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
acc = accuracy_score(Y_test,Y_pred)
cfr = classification_report(Y_test,Y_pred)
cm = confusion_matrix(Y_test,Y_pred)
print("accuracy is : ",acc*100)
print("classification report is \n",cfr)
print("confusion matrix is  \n",cm)

accuracy is :  80.06666666666666
classification report is 
               precision    recall  f1-score   support

           0       0.81      0.97      0.89      2416
           1       0.44      0.08      0.14       584

    accuracy                           0.80      3000
   macro avg       0.63      0.53      0.51      3000
weighted avg       0.74      0.80      0.74      3000

confusion matrix is  
 [[2354   62]
 [ 536   48]]


In [13]:
# RANDOM FOREST CLASSIFIER
from sklearn.ensemble import RandomForestClassifier
rf =RandomForestClassifier()
model = rf.fit(X_train,Y_train)
Y1_pred = model.predict(X_test)

acc1 = accuracy_score(Y_test,Y_pred)
cfr1 = classification_report(Y_test,Y_pred)
cm1 = confusion_matrix(Y_test,Y_pred)
print("accuracy is : ",acc1*100)
print("classification report is \n",cfr1)
print("confusion matrix is  \n",cm1)

accuracy is :  80.06666666666666
classification report is 
               precision    recall  f1-score   support

           0       0.81      0.97      0.89      2416
           1       0.44      0.08      0.14       584

    accuracy                           0.80      3000
   macro avg       0.63      0.53      0.51      3000
weighted avg       0.74      0.80      0.74      3000

confusion matrix is  
 [[2354   62]
 [ 536   48]]


In [14]:
# GRADIENT BOOSTING 
from sklearn.ensemble import GradientBoostingClassifier
gbc = GradientBoostingClassifier()
mdl = gbc.fit(X_train,Y_train)
y_pred = mdl.predict(X_test)

acc2 = accuracy_score(Y_test,y_pred)
cfr2 = classification_report(Y_test,y_pred)
cm2 = confusion_matrix(Y_test,y_pred)
print("accuracy is : ",acc2*100)
print("classification report is \n",cfr2)
print("confusion matrix is  \n",cm2)

accuracy is :  87.0
classification report is 
               precision    recall  f1-score   support

           0       0.88      0.97      0.92      2416
           1       0.78      0.46      0.58       584

    accuracy                           0.87      3000
   macro avg       0.83      0.71      0.75      3000
weighted avg       0.86      0.87      0.86      3000

confusion matrix is  
 [[2342   74]
 [ 316  268]]


In [36]:
#SKB WITH CHI_2: 
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
skb = SelectKBest(score_func=chi2, k=5)
z = skb.fit_transform(X,Y)
fillter = skb.get_support()
filterd_col = X.columns[fillter]
print(filterd_col)

Index(['CreditScore', 'Age', 'Balance', 'IsActiveMember', 'EstimatedSalary'], dtype='object')


In [40]:
x_new = df[['CreditScore', 'Age', 'Balance', 'IsActiveMember', 'EstimatedSalary']]
y_new =df[['Exited']]

Xskb_train,Xskb_test,Yskb_train,Yskb_test = train_test_split(x_new,y_new, random_state =42,test_size = 0.30)

In [41]:
clf = lr.fit(Xskb_train,Yskb_train) 
Y_predSkb = lr.predict(Xskb_test)

acc = accuracy_score(Yskb_test,Y_predSkb)
cfr = classification_report(Yskb_test,Y_predSkb)
cm = confusion_matrix(Yskb_test,Y_predSkb)
print("accuracy is : ",acc*100)
print("classification report is \n",cfr)
print("confusion matrix is  \n",cm)

accuracy is :  80.16666666666666
classification report is 
               precision    recall  f1-score   support

           0       0.81      0.98      0.89      2416
           1       0.45      0.08      0.14       584

    accuracy                           0.80      3000
   macro avg       0.63      0.53      0.51      3000
weighted avg       0.74      0.80      0.74      3000

confusion matrix is  
 [[2357   59]
 [ 536   48]]


In [42]:
# RANDOM FOREST CLASSIFIER

model = rf.fit(Xskb_train,Yskb_train)
Yskb_pred = model.predict(Xskb_test)

acc1 = accuracy_score(Yskb_test,Yskb_pred)
cfr1 = classification_report(Yskb_test,Yskb_pred)
cm1 = confusion_matrix(Yskb_test,Yskb_pred)
print("accuracy is : ",acc1*100)
print("classification report is \n",cfr1)
print("confusion matrix is  \n",cm1)

accuracy is :  82.69999999999999
classification report is 
               precision    recall  f1-score   support

           0       0.85      0.95      0.90      2416
           1       0.61      0.32      0.42       584

    accuracy                           0.83      3000
   macro avg       0.73      0.63      0.66      3000
weighted avg       0.80      0.83      0.81      3000

confusion matrix is  
 [[2294  122]
 [ 397  187]]


In [56]:
# GRADIENT BOOSTING 

mdl = gbc.fit(Xskb_train,Yskb_train)
yskb_pred = mdl.predict(Xskb_test)

acc2 = accuracy_score(Yskb_test,yskb_pred)
cfr2 = classification_report(Yskb_test,yskb_pred)
cm2 = confusion_matrix(Yskb_test,yskb_pred)
print("accuracy is : ",acc2*100)
print("classification report is \n",cfr2)
print("confusion matrix is  \n",cm2)

accuracy is :  84.26666666666667
classification report is 
               precision    recall  f1-score   support

           0       0.85      0.97      0.91      2416
           1       0.73      0.30      0.43       584

    accuracy                           0.84      3000
   macro avg       0.79      0.64      0.67      3000
weighted avg       0.83      0.84      0.82      3000

confusion matrix is  
 [[2351   65]
 [ 407  177]]


In [47]:
# VARIANCE THRESHOLD 
from sklearn.feature_selection import VarianceThreshold
selector = VarianceThreshold(threshold=0.8)
VTX= selector.fit_transform(X)

# Get the indices of the selected features
selected_indices = selector.get_support(indices=True)
# Get the names of the selected features
selected_feature_names = X.columns[selected_indices]
# Print the selected feature names
print("Selected Feature Names:", list(selected_feature_names))


Selected Feature Names: ['CreditScore', 'Age', 'Tenure', 'Balance', 'EstimatedSalary']


In [49]:
x_new1 = df[['CreditScore', 'Age', 'Tenure', 'Balance', 'EstimatedSalary']]
y_new1 =df[['Exited']]

Xvt_train,Xvt_test,Yvt_train,Yvt_test = train_test_split(x_new1,y_new1, random_state =42,test_size = 0.3)

In [50]:
#logistic regression
clf = lr.fit(Xvt_train,Yvt_train) 
Y_predVt = lr.predict(Xvt_test)

acc = accuracy_score(Yvt_test,Y_predVt)
cfr = classification_report(Yvt_test,Y_predVt)
cm = confusion_matrix(Yvt_test,Y_predVt)
print("accuracy is : ",acc*100)
print("classification report is \n",cfr)
print("confusion matrix is  \n",cm)

accuracy is :  80.10000000000001
classification report is 
               precision    recall  f1-score   support

           0       0.81      0.97      0.89      2416
           1       0.44      0.08      0.14       584

    accuracy                           0.80      3000
   macro avg       0.63      0.53      0.51      3000
weighted avg       0.74      0.80      0.74      3000

confusion matrix is  
 [[2355   61]
 [ 536   48]]


In [51]:
# RANDOM FOREST CLASSIFIER

model = rf.fit(Xvt_train,Yvt_train)
Yvt_pred = model.predict(Xvt_test)

acc1 = accuracy_score(Yvt_test,Yvt_pred)
cfr1 = classification_report(Yvt_test,Yvt_pred)
cm1 = confusion_matrix(Yvt_test,Yvt_pred)
print("accuracy is : ",acc1*100)
print("classification report is \n",cfr1)
print("confusion matrix is  \n",cm1)

accuracy is :  80.7
classification report is 
               precision    recall  f1-score   support

           0       0.84      0.94      0.89      2416
           1       0.51      0.26      0.34       584

    accuracy                           0.81      3000
   macro avg       0.67      0.60      0.61      3000
weighted avg       0.77      0.81      0.78      3000

confusion matrix is  
 [[2272  144]
 [ 435  149]]


In [57]:
# GRADIENT BOOSTING 

mdl = gbc.fit(Xvt_train,Yvt_train)
yvt_pred = mdl.predict(Xvt_test)

acc2 = accuracy_score(Yvt_test,yvt_pred)
cfr2 = classification_report(Yvt_test,yvt_pred)
cm2 = confusion_matrix(Yvt_test,yvt_pred)
print("accuracy is : ",acc2*100)
print("classification report is \n",cfr2)
print("confusion matrix is  \n",cm2)

accuracy is :  81.89999999999999
classification report is 
               precision    recall  f1-score   support

           0       0.84      0.95      0.89      2416
           1       0.58      0.27      0.37       584

    accuracy                           0.82      3000
   macro avg       0.71      0.61      0.63      3000
weighted avg       0.79      0.82      0.79      3000

confusion matrix is  
 [[2300  116]
 [ 427  157]]


In [52]:
# SELECT K BEST
from sklearn.feature_selection import SelectKBest, f_classif
fs = SelectKBest(score_func=f_classif, k=5)
fs.fit(X,Y)
selectedFeature = fs.get_support()
lst =X.columns[selectedFeature]
print(lst) 


Index(['Gender', 'Age', 'Balance', 'NumOfProducts', 'IsActiveMember'], dtype='object')


In [53]:
x_new2 = df[['Gender', 'Age', 'Balance', 'NumOfProducts', 'IsActiveMember']]
y_new2 =df[['Exited']]

Xskb1_train,Xskb1_test,Yskb1_train,Yskb1_test = train_test_split(x_new2,y_new2, random_state =42,test_size = 0.3)

In [54]:
clf = lr.fit(Xskb1_train,Yskb1_train) 
Y_predSkb1 = lr.predict(Xskb1_test)

acc = accuracy_score(Yskb1_test,Y_predSkb1)
cfr = classification_report(Yskb1_test,Y_predSkb1)
cm = confusion_matrix(Yskb1_test,Y_predSkb1)
print("accuracy is : ",acc*100)
print("classification report is \n",cfr)
print("confusion matrix is  \n",cm)

accuracy is :  80.53333333333333
classification report is 
               precision    recall  f1-score   support

           0       0.81      1.00      0.89      2416
           1       0.00      0.00      0.00       584

    accuracy                           0.81      3000
   macro avg       0.40      0.50      0.45      3000
weighted avg       0.65      0.81      0.72      3000

confusion matrix is  
 [[2416    0]
 [ 584    0]]


In [55]:
# RANDOM FOREST CLASSIFIER

model = rf.fit(Xskb1_train,Yskb1_train)
Yskb1_pred = model.predict(Xskb1_test)

acc1 = accuracy_score(Yskb1_test,Yskb1_pred)
cfr1 = classification_report(Yskb1_test,Yskb1_pred)
cm1 = confusion_matrix(Yskb1_test,Yskb1_pred)
print("accuracy is : ",acc1*100)
print("classification report is \n",cfr1)
print("confusion matrix is  \n",cm1)

accuracy is :  84.3
classification report is 
               precision    recall  f1-score   support

           0       0.88      0.93      0.91      2416
           1       0.62      0.49      0.55       584

    accuracy                           0.84      3000
   macro avg       0.75      0.71      0.73      3000
weighted avg       0.83      0.84      0.84      3000

confusion matrix is  
 [[2244  172]
 [ 299  285]]


In [58]:
# GRADIENT BOOSTING 

mdl = gbc.fit(Xskb1_train,Yskb1_train)
yskb1_pred = mdl.predict(Xskb1_test)

acc2 = accuracy_score(Yskb1_test,yskb1_pred)
cfr2 = classification_report(Yskb1_test,yskb1_pred)
cm2 = confusion_matrix(Yskb1_test,yskb1_pred)
print("accuracy is : ",acc2*100)
print("classification report is \n",cfr2)
print("confusion matrix is  \n",cm2)

accuracy is :  86.76666666666667
classification report is 
               precision    recall  f1-score   support

           0       0.88      0.97      0.92      2416
           1       0.78      0.45      0.57       584

    accuracy                           0.87      3000
   macro avg       0.83      0.71      0.74      3000
weighted avg       0.86      0.87      0.85      3000

confusion matrix is  
 [[2342   74]
 [ 323  261]]
